myproject/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.HomePage.as_view(),name='homepage'),
    path('blog/',views.HomePage.as_view(),name='homepage'),
    path('blog/blogs/',views.BlogListView.as_view(),name='bloglistview'),
    path('blog/<int:pk>/',views.BlogDetailView.as_view(),name='blogdetailview'),
    path('blog/blogger/<int:pk>/',views.AuthorDetailView.as_view(),name='authordetailview'),
    path('blog/bloggers/',views.AuthorListView.as_view(),name='authorlistview'),
    path('blog/<int:pk>/create/',views.CommentPage,name='commentpage'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/',include('user.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

myproject/user/urls.py
from django.urls import path
from . views import register_request

app_name = 'user'
urlpatterns = [
    path('signup/',register_request,name='signup')
]

myproject/blog/models.py
from django.db import models
from datetime import datetime


class Author(models.Model):
    name = models.CharField(max_length=100)
    about_author = models.TextField()

    def __str__(self):
        return self.name


class Blog(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    posted_date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment_content = models.TextField()
    commented_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content

myproject/user/models.py
from django.db import models

# Create your models here.

myproject/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_content']

myproject/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "id-NewUserForm"
        self.helper.form_class = "blueForms"
        self.helper.form_method = "post"

        self.helper.add_input(Submit("submit", "SignUp"))

myproject/blog/views.py
from django.views.generic import TemplateView,ListView
from .models import Blog,Author,Comment
from django.shortcuts import render,redirect
from .forms import CommentForm
from django.contrib.auth.decorators import login_required

class HomePage(TemplateView):
    template_name = 'blog/homepage.html'

class BlogListView(ListView):
    template_name = 'blog/bloglistpage.html'
    queryset = Blog.objects.order_by('-posted_date')
    paginate_by = 5

class BlogDetailView(ListView):
    model = Comment
    template_name = 'blog/blogdetailpage.html'

    def get_queryset(self):
        queryset = super().get_queryset().filter(blog_id = self.kwargs['pk']).order_by('commented_date')
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["context"] = Blog.objects.filter(id = self.kwargs["pk"]).first()
        return context

class AuthorDetailView(ListView):
    model = Blog
    template_name = 'blog/authordetailpage.html'
    context_object_name = 'author_detail'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author_id=self.kwargs["pk"]).order_by('-posted_date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["context"] = Author.objects.filter(id=self.kwargs["pk"]).first()
        return context

class AuthorListView(ListView):
    template_name = 'blog/authorlistpage.html'
    queryset = Author.objects.all()

@login_required(login_url='/accounts/login/')
def CommentPage(request,pk):
    blog = Blog.objects.filter(pk=pk).first()
    if request.method == "POST":
        form = CommentForm(request.POST) 
        if form.is_valid():
            obj = form.save(commit=False)
            obj.blog_id = blog.pk
            obj.save()

            return redirect('blog:blogdetailview',pk)
    else:
        form = CommentForm()

    context = {
        'blog_' : blog,
        'form' : form,
    }            
    return render(request,'blog/commentcreatepage.html',context)

myproject/user/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib.auth.decorators import user_passes_test

def user_not_logged_in(user):
    return not user.is_authenticated

@user_passes_test(
    user_not_logged_in, login_url="blog:homepage", redirect_field_name=None
)
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("blog:homepage")
    form = NewUserForm()
    return render(
        request=request, template_name="user/register.html", context={"form": form}
    )

myproject/blog/templates/blog/authordetailpage.html
{% extends 'base.html' %}
{% block title %} Author Detail Page {% endblock %}
{% block extra_css %}
<style>
    p{
        font-size: large;
    }
    a.blog{
        text-decoration: none;
        font-size: large;
    }
    a.blog:hover{
        color: green;
        font-size: larger;
    }
    .header {
        padding: 10px;
        font-size: 25px;
        text-align: center;
    }
    .author{
        padding: 5px;
    }
    #aboutauthor{
        font-size: 30px;
        font-weight: bold;
    }
    

</style>
{% endblock %}
{% block content %}
<div class="header">
    <h1> {{context.name}} </h1>
</div>
<div class="author">
    <p id="aboutauthor">About Author:</p>
    <p>{{context.about_author}}</p>
</div>

<h3>Blogs by this author are given below: </h3>
{% for blog in author_detail %}
<ul>
    <li>
        <a class="blog" href="{% url 'blog:blogdetailview' blog.id %}">{{ blog.title }}</a>
        <span>{{blog.posted_date}}</span>
    </li>
</ul>
{% endfor %}
{% endblock %}

myproject/blog/templates/blog/authorlistpage.html
{% extends 'base.html' %}
{% block title %} Author List Page {% endblock %}
{% block extra_css %}
<style>
    h1{
        color: white;
    }
    a.author {
        text-decoration: none;
        font-size: large;
        color: white;
    }

    a.author:hover {
        color: rgb(157, 201, 157);
        font-size: larger;
    }

    /* Author List Container */
    .author-list {
        display: flex;
        flex-direction: column;
        flex-wrap: wrap;
        justify-content: space-between;
        background-color: #0b0b0b;
        padding: 1rem;

    }   
</style>
{% endblock %}
{% block content %}
<div class="author-list">
    <h1>Authors:</h1>
    {% for author in object_list %}
    <ul>
        <li>
            <a class="author" href="{% url 'blog:authordetailview' author.id %}">{{author.name}}</a>
        </li>
    </ul>
    {% endfor %}
</div>

{% endblock %}

myproject/blog/templates/blog/blogdetailpage.html
{% extends 'base.html' %}
{% block title %} Blog Detail Page {% endblock %}
{% block extra_css %}
<style>
    p {
        font-size: large;
    }

    a.comment {
        text-decoration: none;
        font-size: larger;
    }

    a.comment:hover {
        color: green;
        font-size: 30px;
    }

    .header {
        padding: 10px;
        font-size: 25px;
        text-align: center;
    }
    .date-writer {
        text-align: right;
        font-size: large;
        font-style: italic;
    }
    #comments{
        border: 1px solid black;
        border-radius: 5px;
        
    }
    #comments > p{
        font-size: 30px;
        font-weight: bold;
        margin-left: 10px;
    }
    #comments li p{
        font-size: 20px;
        border: 1px solid grey;
        padding: 3px;
        border-radius: 5px;
        color: white;
        background-color: rgb(37, 35, 35);
    }
    #comments li{
        list-style-type: square;
    }
    .below-content{
        margin: 10px;
    }
    
</style>
{% endblock %}
{% block content %}
<div class="header">
    <h1>{{ context.title }}</h1>
</div>
<div>
    <p class="date-writer"><span>Posted on :</span>{{context.posted_date}}</p>
    <p>{{ context.content }}</p>
    <p class="date-writer" ><span>Written by :</span>{{context.author.name}}</p>
</div>
<div id="comments">
    <p>Comments : </p>
    {% for com in object_list %}
    <ul>
        <li>
            <p>{{com.comment_content}}</p>
            <span>{{com.commented_date}}</span>
        </li>
    </ul>
    {% endfor %}
</div>
<div class="below-content">
    <a class="comment" href="{% url 'blog:commentpage' context.id %}">Click here to add Comments</a>
</div>
{% endblock %}

myproject/blog/templates/blog/bloglistpage.html
{% extends 'base.html' %}
{% block title %} Blog List Page {% endblock %}
{% block content %}
{% block extra_css %}
<style>
    .container li{
        padding: 10px;
        font-size: large;
        list-style-type: decimal;

    }
    .container a:hover,.pagination a:hover {
        color: green;
        font-size: larger;
    }
    .link-update{
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        font-size: large;
    }
    .container span{
        padding: 5px;
        margin: 10px;
        border: 2px solid white;
        border-radius: 5px;
        color: white;
        background-color: black ;
    }
    .pagination{
        margin-left: 45%;
        bottom: 70px ; 
        position: absolute; 
    }
   
    .step-links{
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        font-size: 40px;
        font-weight: bold;
    }
    .container {
        
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    margin-top: 2rem;
}
.blog-list__item {
    width: 32%;
    margin-bottom: 2rem;
    box-shadow: 0px 0px 10px #ccc;
    border-radius: 5px;
    overflow: hidden;
}
</style>
{% endblock %}
<div class="container">
    <ul>
        {% for blog in page_obj %}
        <li>
            <a class="link-update" href="{% url 'blog:blogdetailview' blog.id %}">{{blog.title}} </a>
            <span> {{blog.posted_date}}  </span>
            <a class="link-update" href="{% url 'blog:authordetailview' blog.author_id %}">{{blog.author}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="pagination">
    <footer>
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a class="link-update" href="?page=1">&laquo; first</a>
            <a class="link-update" href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a class="link-update" href="?page={{ page_obj.next_page_number }}">next</a>
            <a class="link-update" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </footer>

</div>
{% endblock %}

myproject/blog/templates/blog/commentcreatepage.html
{% extends 'base.html' %}
{% block title %} Blog Detail Page {% endblock %}
{% block extra_css%}
<style>
    /* Form Container */
    form {
        width: 80%;
        margin: 2rem auto;
        padding: 2rem;
        border: 1px solid #ccc;
        border-radius: 10px;
        background-color: #f8f8f8;
    }

    /* Form Label */
    label {
        font-size: 1.2rem;
        font-weight: bold;
        margin-bottom: 0.5rem;
        display: block;
    }

    /* Form Input */
    input[type="text"],
    textarea {
        width: 100%;
        padding: 0.5rem;
        margin-bottom: 1.5rem;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 1.2rem;
    }


    /* Form Submit Button */
    input[type="submit"] {
        background-color: #ffffff;
        color: black;
        padding: 0.75rem 1.5rem;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1.2rem;
    }

    /* Form Submit Button - Hover */
    input[type="submit"]:hover {
        background-color: #040504;
        color: rgb(255, 255, 255);
    }
</style>
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <label for="blog_title">Title : </label>
    <input type="text" name="blog_title" id="blog_title" value="{{blog_.title}}" size="100%" disabled><br><br>
    <label for="blog_content">Content :</label>
    <textarea name="blog_content" id="blog_content" rows="5" cols="60" disabled>{{blog_.content}}</textarea><br><br>
    <label for="posted_date">Posted Date : </label>
    <input type="datetime" name="posted_date" id="posted_date" value="{{blog_.posted_date}}" disabled><br><br>
    {{form}} <br><br>
    <input class="openbtn" type="submit" value="Post Comment">
</form>
{% endblock %}

myproject/blog/templates/blog/homepage.html
{% extends 'base.html' %}
{% block title %} Home Page {% endblock %}
{% block extra_css %}
<style>
    h1{
        text-align:center;
        font-size: 50px;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
    .homepage p{
        font-size: large;
        text-align: center;
        font-family: 'Times New Roman', Times, serif;
    }
</style>
{% endblock %}
{% block content %}

<div class="homepage">
    <h1>Welcome {{ user.username }}!</h1>
    <p>Thank you for visiting our blog. We're glad you're here and excited to share our thoughts and experiences with you.
        Our blog is dedicated to providing valuable and informative content on a variety of topics including travel,
        personal development, and more.</p>
    <p>We believe that everyone has a unique perspective to share and we welcome you to share your own thoughts and
        experiences in the comments section of our posts. We also encourage you to sign up for our newsletter to stay
        updated on our latest posts and events.</p>
    <p>Again, welcome to our blog. We hope you enjoy reading our posts and find them informative and inspiring.</p>
</div>

{% endblock %}

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Base {% endblock %}</title>
    <style>
        body {
            font-family: "Lato", sans-serif;
        }
        .user{
            color: white;
            font-size: 30px;
            margin: 0 10px;
        }
        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

        .sidebar a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidebar a:hover {
            color: #f1f1f1;
        }

        .sidebar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        .openbtn {
            font-size: 20px;
            cursor: pointer;
            background-color: #111;
            color: white;
            padding: 10px 15px;
            border: none;
        }

        .openbtn:hover {
            background-color: #444;
        }

        #main {
            transition: margin-left .5s;
            padding: 16px;
        }

        /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
        @media screen and (max-height: 450px) {
            .sidebar {
                padding-top: 15px;
            }

            .sidebar a {
                font-size: 18px;
            }
        }
    </style>
    {% block extra_css %}
    {% endblock %}
</head>

<body>

    <div class="sidebar" id="mySidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">x</a>

        {% if user.is_authenticated %}
        <p class="user">Hi {{ user.username }}! Welcome to this blog site...</p>



        <p><a href="{% url 'logout' %}"> Log Out </a></p>
        {% else %}
        <p class="user">You are not logged in...Please login first. </p>
        <p><a href="{% url 'login' %}"> Log In </a></p>
        <p class="user">If you do not have an account..Then Sign Up first..</p>
        <p><a href="{% url 'user:signup' %}"> Sign Up </a>
        {% endif %}

        </p>
        <ul>
            <li>
                <a href="{% url 'blog:bloglistview' %}"> All Blogs </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="{% url 'blog:authorlistview' %}"> Authors </a>
            </li>
        </ul>
    </div>
    <div>
        <button id='openbtn' class="openbtn" onclick="openNav()">☰</button>

    </div>
    <div id="main">
        {% block content %}
        {% endblock %}
    </div>
    <script>

        function openNav() {
            document.getElementById("mySidebar").style.width = "350px";
            document.getElementById("main").style.marginLeft = "350px";
            document.getElementById('openbtn').style.display = "none";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
            document.getElementById('openbtn').style.display = "block";

        }

    </script>
</body>

</html>

myproject/user/templates/user/register.html
{% extends 'base.html' %}
{% block title %} Blog Detail Page {% endblock %}
{% block extra_css %}
<style>
    p {
        font-size: large;
    }

    a.signup {
        text-decoration: none;
        font-size: 25px;
    }

    a.signup:hover {
        color: green;
        font-size: 30px;
    }
    .blueForms form {
        width: 80%;
        margin: 2rem auto;
        padding: 2rem;
        border: 1px solid #ccc;
        border-radius: 10px;
        background-color: #f8f8f8;
    }

    /* Form Label */
    label {
        font-size: 1.2rem;
        font-weight: bold;
        margin-bottom: 0.5rem;
        display: block;
    }

    /* Form Input */
    input[type="text"],
    input[type="email"],input[type="password"]
    {
        width: 100%;
        padding: 0.5rem;
        margin-bottom: 1.5rem;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 1.2rem;
    }


    /* Form Submit Button */
    input[type="submit"] {
        background-color: #030202;
        color: rgb(172, 167, 167);
        padding: 0.75rem 1.5rem;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1.2rem;
    }

    /* Form Submit Button - Hover */
    input[type="submit"]:hover {
        background-color: #838583;
        color: rgb(6, 5, 5);
    }
</style>
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div>

    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
    <p>If you already have an account ,then go to the <a class="signup" href="{% url 'login' %}">Log In</a> page.</p>
</div>

{% endblock %}